name: Guthub action
on:
  workflow_dispatch:
    inputs:
      name:
      required: true
      description: python version
      default: python3.8

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }} 
     
  
   
